### ISSUE TITLE
에러 및 기능 이슈

### ISSUE THREAD

**Issue by ForteEscape** [etilelab/AccountBook-BlockChain#6]
1. 회원가입 창에서 특수문자  '_' 사용이 가능합니다.(shift -)

2. 통계페이지 진입 문제 int() argument must be a string, a bytes-like object or a number, not 'NoneType'
    에러가 뜨면서 진입이 되지 않습니다.

3. 전자장부 창에서 각 분류를 확인할 수 있는 방법이 사용내역에서밖에 확인 할 수 없습니다. 
    확인이 가능하도록 각 옵션을 표시 할 수 있는 줄을 만들어야 할 것 같습니다.

4. 장부 검색에 지출, 회비, 수입의 필터가 아직 없습니다 만들어야 할 것 같습니다.

5. 통계 페이지에 로그아웃 버튼이 사라져 있습니다.

1, 2 는 보안 및 내부 버그이고 3, 4, 5 는 사용하면서 느낀 불편함 입니다.

**Comment by etilelab** [comment]
1. [해결] email은 '_' 포함될수있게, password 에서는 포함될수 없게 sec.py 수정
2. [해결] 통계페이지 SQL파일 재설정시 해결
3. [해결] 장부 테이블에 수입/지출/회비 열 추가
4. [생략]
5. [해결] 최신 AccountBook0BlockChain.py 로 동기화
